:day: Day02
= {day}

To run the program, you need JDK 11.
Thanks to http://openjdk.java.net/jeps/330[JEP 330], launching is as easy as `java {day}.java`.

== Part 1

Method to evaluate validity of the password:

[source,java, linenums]
----
include::{day}.java[tags=part1]
----

<1> (up to line 8): parse the policy (the character `c` in question, as well as min and max allowed occurences)
<2> extract the actual password
<3> count occurences of the character in question. Note that `chars()` returns an `IntStream` (since there is no such thing as a `CharStream`)!
<4> evaluate validity of the password

Get the solution:

[source,java, linenums]
----
include::{day}.java[tags=part1Eval]
----

<1> Read the input into a list of Strings
<2> Use a stream to filter for valid passwords, using the above method and count them

== Part 2

[source,java, linenums]
----
include::{day}.java[tags=part2]
----

<1> (up to line 8): parse the policy, interpreting the digits as positions
<2> extract the actual password
<3> count charachter occurences at the positions
<4> password is valid  if there is exactly one occurence of the password at the two positions

Get the solution (same as for Part 1, but using the other method):

[source,java, linenums]
----
include::{day}.java[tags=part2Eval]
----

