== Day 1: Report Repair ==

Run solution with `cargo run`

The solution for both parts is about iterating through all https://en.wikipedia.org/wiki/Combination[combinations] of two or three elements in the first and second part respectively and find a combination which sums up to 2020.

With a tip of Sven H., I found that Rust https://docs.rs/itertools[itertools] have the `tuple_combinations` iterator adaptor, which results in very clean code.
Here is how solution of part 2 looks like (part 1 is very similar):

=== Solution ===

[source,rust,numbered]
....
include::src/lib.rs[tags=solve_n3]
....

=== Alternative solutions ===

A generic method which takes the size of the combination as a parameter looks as follows:

[source,rust,numbered]
....
include::src/lib.rs[tags=solve_with_itertools]
....

The generic variant is much slower than the specific ones (~1 ms vs ~20 ms for part 1).

I do not understand why I need to map `|a| *a` and `into_iter()` is not working for the sum as it does for the product.

Another generic variant looks like this:

[source,rust,numbered]
....
include::src/lib.rs[tags=solve_with_while]
....

Performs better than the variant above but still significantly slower than the specific variants.

=== Insights / Learnings ===

Tried the Cargo feature to run example code in documentation as tests to make sure the examples actually work.
To do so, I had to move the functions to a ``src/lib.rs``.

Also learned about what difference compiler optimization makes:

.Debug profile without optimization (`cargo build`)
----
Solved part 1 with tuple combinations in 1369 us -> 381699
Solved part 1 with itertools::combinations in 17158 us -> 381699
Solved part 1 with while loop in 3539 us -> 381699
Solved part 2 with tuple combinations in 55535 us -> 111605670
Solved part 2 with itertools::combinations in 627991 us -> 111605670
Solved part 2 with while loop in 130939 us -> 111605670
----

.Release profile with optimization level 3 (`cargo build --release`)
----
Solved part 1 with tuple combinations in 23 us -> 381699
Solved part 1 with itertools::combinations in 1952 us -> 381699
Solved part 1 with while loop in 66 us -> 381699
Solved part 2 with tuple combinations in 1692 us -> 111605670
Solved part 2 with itertools::combinations in 52095 us -> 111605670
Solved part 2 with while loop in 3158 us -> 111605670
----