image:
  file: .gitpod.dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
  - command: source /home/gitpod/.sdkman/bin/sdkman-init.sh
vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - asciidoctor.asciidoctor-vscode@2.8.4:9qifXNFuJwslDFbQfIgkCA==
