
Day 10 of year 2020
https://adventofcode.com/2020/day/10


== What I learned

. I finally used a list comprehension successfully. The code is a bit more compact than in the previous days.

== Approach

. I read the file in using .readlines.
. I process the file data. Just take each line and turn it into an integer.
. For part 1:
.. I add '0' and 3 more than the maximal adapter to the list. And then sort it.
.. And then just find the difference between adjacent adapters and do the required math.
.. This part was pretty straightforward.
. For part 2
.. I found a solution that works if the adapters difference is never 2. None of the examples had a difference of 2 in it. My file didn't have a difference of 2 either.
... I split up the list of differences along the 3 entries. And then for each of these fragments, I calculate the number of combinations with a recursion.
.... I think this should also somehow work if you have differences of 2, but I haven't figured it out yet...
.. After searching around, I found another way to find the combinations that in fact does work with differences of 2. You go through the list of adapters and find which other adapters are no more than 3 away from it. You add up over the list of adapters then the combinations iteratively.

== Run script
Run the solution with `python solution.py`

[source, python]
....
include::solution.py[]
....