== Day 20: Jurassic Jigsaw ==

Rust solution for https://adventofcode.com/2020/day/20[AoC 2020, Day 20]

Run solution with `cargo run` (or `cargo run --release` to see the effect of compiler optimization)

Run tests with `cargo test`

=== Solution ===

A day to forget.
Just got lost in transformations...

It's a lot about transformations. There are eight in total to represent all possible rotations and flips (see comments in code below). Those transformations are applied to a _flat_ index `idx = x + n * y`, where `n` is the width of a square tile. The function below yields data at a given coordinate after transformation:

[source,rust,numbered]
----
include::src/lib.rs[tags=get_set_transform]
----

This is used, e.g., to check whether two tiles match on a given side (0: top, 1: right, 2: bottom, 3: left). The transformation of the tile on which the function is called is given as an argument (`t`), the matching transformation of the tile provided as an argument, if any, is returned by the function.
If there is none, the function returns `None`.

[source,rust,numbered]
----
include::src/lib.rs[tags=match]
----

The biggest part for me was to arrange the tiles.
My first version started from an arbitrary tile and worked for the example but not for the real data.

Since I could not figure out my problem, I first created a solution for part 1 by finding all corner tiles, i.e., all tiles which do not match to any other tile on two sides.

Once I had that, I just kept the part to find one corner tile and created the solution below which constructs the solution from a corner tail.

The function `find_corner` below finds a corner tile as described above and provides a transformation (rotation), that ensures the two boundaries not matching to any other tile are in the top and left directions.

[source,rust,numbered]
----
include::src/lib.rs[tags=find_corner]
----

From this, the solution is constructed row by row as follows:

[source,rust,numbered]
----
include::src/lib.rs[tags=solve]
----

For the second part, the picture is constructed as follows:

[source,rust,numbered]
----
include::src/lib.rs[tags=get_picture]
----

And the monster is searched in the picture using

[source,rust,numbered]
----
include::src/lib.rs[tags=get_picture]
----

I was happy that the monsters do not overlap (at least in my case). That made calculating the roughness very easy:

[source,rust,numbered]
----
include::src/lib.rs[tags=get_roughness]
----

A bit of artwork to conclude:

.The Sea
----
.....#....#........#.......#........##.##.............#.........###.....#...##..................
.#....#..#....#.##..#..##.#....#..#.#.##..#.......#.....#.........#.##..#...#.#.....###.....##..
.##..........#..##..#.....###......#.......#..........#.###....#........#....#..#.....#..##..#..
.##....#......#......#.##....#.._.#..........#...##......#...##...#....#.#..#...#......#...##..#
..#....#......\..#./\..#./\...#/o>#........#.......#...##.#.##..#.#.#...#.#._..##..#...##..#....
#.....#.....#..\../..\../#.\.#/#.##........#.......#..#...\...#/\..../\..../o>.#...#........#...
...#..#...#.##.#......##......#.....#.....#........#.#..#..\../##\../#.\../...#...........#.....
..#.........#.............#.........#...#.....##..........#.....#...#...##.......#.#.........#..
........#......#.................#....#...#..#...##.#..#.#....#.........#.##..#.##............#.
.#.#......#.##.............####....#.#..............###....._..........##.#.##......#..#_.#....#
#.....##.#.#....#....#............#....#..\..#./\..../\..../o>#.#....#\#.../\..##/\..../o>......
.....#..###.......#.._..........##.#.#.#...\../..\../..\##/..#....##.#.\#./#.\../..\../...#...#.
.#.\..../\#.../\..##/o>..#.#.....##.#.#..........##.............#......#..##...#.#..#...#..#..#.
#..#\../..\../.#\../..#.....#.#..#.#..............#....#..###.#._#.......##.......##.##..#......
.#...#..#..#.#...........#.....#......#.....#.\.#../\.##./\.#../o>#.##...#..#.....#...##.#......
#.#...##.....#....###.##.....#.............##..\../..\.#/..\.#/.#.#.#....#..#.....#.##....._#...
......##.............#..##.#.._###..#........#.##....##......##.##....#..\#.../\..../\..../o>..#
.........#.#\..#./\.#../\..#./o>#...###..#.#.......#....#....#..#.#.#..###\#./..\#./#.\../......
#...#..#...#.\../#.\../.#\../..........#.#.......#.#.#_...............#.........#....#..#.......
.#.#...#.#..........#.#.#.#..#.....#\#.../\##.#/\..##/o>.#.....#.###..#......#......##...#.....#
......#.#..#...........#..#.......#..\#./.#\../..\../.......#.....#....#....#..............##..#
#...#...#..#..##.###..##....#..#..#..#...#.#..........##..#..#..............#...#.....#........#
.#..........#.##......#......##_#........#..................#..._#.##...##....#....#............
.#.#.#.#...#.\...#/\##../\...#/o>.#....#...#..\##../\...#/\..#./o>#................#..#.....##..
..#....##.#...\#./##\##/..\../........#..##.##.\../#.\../..\.#/......###........##....#._...#...
##.......#...#.....#...##....##....#..#..#.##...##.....#.....#........\..../\.#../\.#../o>...#..
..........#..##......#..###.#......#.##....###.......##................\../.#\.#/#.\../.....#...
...#.....#..........#....#_.......#..#....#...#.##...#._#.....##...#...##..#....##....#.....##..
..#....#\#.../\.###/\.#../o>.....#...\...#/\...#/\#.../o>.###................##.............#...
....#....\../..\../..\../##.#.....#.##\#./.#\#./..\../........#..#..#..#..#.#.#..##...#...#.....
##.......#.................#....#..#.............##..#.#.......#....#.....#...##.....#.#....#...
.....#..##.#.....#.##.##.......#.##.#...#...#..#.####..###.....#.#.##..................#.#..####
##....##.#............#.........#....#..........#.##...#.....#.#..#.#.....#.....##...##..._.....
.....##.......#.....#.....#...._.......#..#.........#.....#......._....#\.#../\####/\.#../o>.#..
.......#.....\..../\...#/\###./o>.#..#...#.##.#.\..../\..#./\#.../o>.#..#\#./..\.#/#.\../.##....
..........###.\#./#.\../.#\.#/.#.......#....##...\.#/#.\#./..\../.#..#...#...#...#..#.....###...
.#.........#.#....##..........#......#.#......#....#..#........#...#..#.##......##........#..#..
#....#.#.#.#...##..##..#...#.##.#..##.#.#..#.....................###.###.....#.##........._#....
......#.#..#.............#...#..#.....#..#.....##..........#.....##.#...\...#/\#.#./\..../o>....
..#......#.#.#.#.#.#.#...#.#...._#...........##.#.##.......#.....#...#..#\../#.\#./..\.#/...#..#
#...#..#.#.#..\#..#/\#.../\##.#/o>...##.#.#.#.#...##.....#...#_.#...#...#........##..##....##..#
...#..#........\#./#.\.#/..\../##.#.........\..../\#.../\#.../o>..#....#..####.###..#.#.........
.#...#.......#.....##.#.#........#.#...#....#\../..\#./#.\../#...#.#........#..##..#..........#.
.....#............##..#..###.......#...#.#..#....#.#..###......#.#......#......#...#.........#..
...#..##.#...#...#..#.#...#.#....#.....#.............##.#...##.#...#....#..#...#....##.#.#......
..#..##.#.........#..#.....#.._#..#.#........###...#....#.....#.._......#...#..............#_...
............\..#./\.#../\..../o>#....#....#....\..../\.#../\..../o>....#..\..#./\..../\..../o>..
....##.##....\../#.\../#.\../##....##..##..#...#\#./.#\../..\.#/..#.##....#\../..\../.#\.#/.....
.........#......#.#.##.#..#.#....#..#...#...##.#.......#......#...#.........#..#......###....##.
##....#.....#..#...##...#..#..#..#..#....####.......#..#..#..##...#.#..#.#.#..#...#.....#....###
.#...#.#.....#.....#.##..##.#.#..#.....#......##.........##.._......#..##.#......#.#....##......
...#......#....#.......#.#.#..#..#....._..#\.##./\...#/\#.../o>##.#..#......#.#.##..##.._.#.##.#
##......#..#..#......\..../\#.../\.#.#/o>...\../..\../#.\.#/......#.#.\#.#./\..../\##../o>......
.......##.#.#..##.....\../..\#./#.\.#/..#....##.##............##.......\../..\../#.\#./..#.##..#
.#.#....##....#.......#.....#....#..#.###.#.#.#...#..#..#.##...#........##.#......#..##....#....
##....#........##.#....#.......#.###.#.......#...#....##..###....#.#....#...#....#.......#......
.#.....###......#..#._......##.#.......##..#........###.#.............#.#..#_....#.........#..#.
#.#\#.../\..../\..../o>.....##.......#...##..#..#....#...#\..../\..../\..../o>.......#.#........
##..\#./..\../.#\../#........##..#......#.##....#.##...#...\.#/#.\../..\#./................###.#
#.##..........#.#.###..##......#...#.......#_##...###.#......#................#....##..###.#...#
##.##.#..#........#.#.....\..../\.###/\...#/o>.#.##..#.....#.............##........##.#...#..#..
.......#.#....#.......#....\##/..\../..\../#..#.##.....##.#.....#.##....#...###._...#.##........
.........#.#..#.#.#..._..#...#.##........##.#.....#.####......\.#../\..../\..../o>......#....##.
...#\.#../\..../\..../o>##.....#....#.##........#.....#...##.#.\../.#\#./#.\../......##.#.#..#.#
.#...\.#/..\../..\.#/.....#..###..#.#........#.....#.....#....##...#......#.#.#..........##.#...
....#.#.....#.##..#..#...#...#.......#.......#....#.._.....#......#...#......#..#...#.......#.#.
.###.#....##..###.###..###...#.#...\..../\..../\.#../o>.#......#........#.##...#.#.#...#.....#..
......#....#..#......#......._...#..\.#/..\../..\../.#..#.#..###......#....#......##....##..##..
..#.......#\#.../\##../\#.../o>.##...#...#.#.........##...##...#.........##......_#..##.....#..#
.##.........\##/#.\.#/#.\../......#...#.#..........#...#.#..##.\###./\..../\..../o>..#..##......
.....#.###...##..........###....#.#.......#.......#..#....._....\##/..\../##\.#/..........#.....
........#.......#..................#..###\...#/\...#/\.#../o>.#...##.....##.....................
.##........#....###.##.#.#....#..#.....#..\##/..\../..\.#/....##...#......#.#...#...#..#.#..#...
.......#...#......#........#...##..#....#.##.....#.#....#........#.#.#.............#.....#....#.
#.###...#..#..#.....#.........#....#..#.........#..#...............##.#..........#.....##.......
#.#..#.....##..#..##.#_....#......##..#...#.##....#......#.#.....#....._....#.#..#.#.....#......
#...\##../\..../\.#../o>.....#..#..#...#.....###..#..\.##./\##../\..../o>....#.....#.....#.#...#
.#...\../..\#./#.\../.##....#....#......#.#.#...#.....\../#.\../..\#./....#...........#..#..#.##
#.........###..#.##...........#..#.#.#.#....#.....##....#.#............##...#.......#.#...##....
...........#...#....#......._...................#.##.......##....#...##..#....#...##...##.......
##.....#.#\..../\#..#/\..#./o>.....###..#....##..##........##..........#.#..#.....#...##........
.###....###\../#.\../.#\../.#.....#.........#...##.#.....##.##.##........#..##...#...#.#........
...#.......#...#.#..##.##....##.#..#...#.......#.......#....##.#.#.##...._.#......###...........
......##........#..#.#...#..............#....#....#_...\...#/\.###/\#.../o>.##..####......#....#
.#.###...........#.#.....#.......\..##/\..#./\..../o>...\#./..\#./..\../..#..##.....#.###.#.....
.....#.....#.#...#...##.#..##.#..#\.#/..\../..\.#/....#..###.##.....#...#.##....#..##..#..#.####
#.#.###.#...#....#..#.......#......#.#.#..#..#....#.......#.#..#...#.#..#..#...##....#..........
..##......#.#.....##._........#.#....#...#..#..#...........#.....#..#..#...#............#......#
..#\#.../\####/\..##/o>...##.....#............._#..#..........#...#..#..#....._......#...#..##..
.#..\##/..\../..\../#........\..../\.#../\..../o>##.....#...\..../\..../\...#/o>.......#.....#..
...#........##...#..#....#....\.#/.#\../..\../..#...##.......\#./..\../..\../...###.#..#....#..#
#...#.##...#...........#..#..#..#.#..#.......#........#.####..#..##.......#.....##...##.#...##..
#..............#....##.##..#..#...........###.#.......#..#..........#..##.......#.#.#......#...#
..##.#.#....##...............#.......#...........#....##.......###......#..............#...#.#..
.....#...#.#...#..#...##....#.#......#.....#....#...###.....##....#..#..#...#.....###.##..##....
..........#............#.........##...#.#........#...............##.......#...#..#....#.#....##.
----
