== Day 19: Monster Messages ==

This solution is written in Kotlin.

The original puzzle can be found at https://adventofcode.com/2020/day/19

 $ kotlin day2019_1_2.kts
 
=== First Star

How does it work: +

The today's task gave me a little bit of headache. My main problem was, how to interprete the rule-set with low effort. After some time I remembered some discussion about regular expressions on our slack channel. I never worked with regex before, but after some googling I found it worth to learn something about it.

In my solution the rules are read into a map. Out of this ruleset the regex pattern is generated by replacing all the rules starting from rule 0 by sub-rules until the pattern contains no sub-rules any more (or only "a", "b"). Each reaplacement is put into brackets, this is a overhead, but makes generation of the mattern more easy.

In order not to generate some faults by replacing e.g. rule 14 into 114, I added spaces before and after each number, so I could work still with strings. Spaces and quotation marks are removed at the end.

While doing so, I had much fun in learning something about regular expressions, and also the code itself looks pretty simple.

[source, kotlin, numbered]
....
include::day2019_1_2.kts[tags=prepare_ruleset]
....

After that, all messages out of the puzzle input are checked if matching the pattern.

[source, kotlin, numbered]
....
include::day2019_1_2.kts[tags=check_messages]
....

=== Second Star

How does it work: +

This works the same way as part1, with some modifications. Since the rules-set is infinte, I create a first turn of a pattern and calculate the matching messages. If this number is not zero and not the same value of matching messages as before, I will start this loop again and create a next turn of pattern, so adding more an more loops into the regex pattern until matching messages do not increase anymore.

[source, kotlin, numbered]
....
include::day2019_1_2.kts[tags=pre_ruleset_check_mes]
....

Finally, print out the solution for both puzzles:
[source, kotlin, numbered]
....
include::day2019_1_2.kts[tags=output]
....